In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math

In [2]:
mitbihTestdf = pd.read_csv("mitbih_test.csv")
mitbihTraindf = pd.read_csv("mitbih_train.csv")
ptbdbNormaldf = pd.read_csv("ptbdb_normal.csv")
ptbdbAbnormaldf = pd.read_csv("ptbdb_abnormal.csv")

In [3]:
mitbihTraindf

,9.779411554336547852e-01,9.264705777168273926e-01,6.813725233078002930e-01,2.450980395078659058e-01,1.544117629528045654e-01,1.911764740943908691e-01,1.519607901573181152e-01,8.578431606292724609e-02,5.882352963089942932e-02,4.901960864663124084e-02,...,0.000000000000000000e+00.79,0.000000000000000000e+00.80,0.000000000000000000e+00.81,0.000000000000000000e+00.82,0.000000000000000000e+00.83,0.000000000000000000e+00.84,0.000000000000000000e+00.85,0.000000000000000000e+00.86,0.000000000000000000e+00.87,0.000000000000000000e+00.88
0,0.960114,0.863248,0.461538,0.196581,0.094017,0.125356,0.099715,0.088319,0.074074,0.082621,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.000000,0.659459,0.186486,0.070270,0.070270,0.059459,0.056757,0.043243,0.054054,0.045946,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.925414,0.665746,0.541436,0.276243,0.196133,0.077348,0.071823,0.060773,0.066298,0.058011,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.967136,1.000000,0.830986,0.586854,0.356808,0.248826,0.145540,0.089202,0.117371,0.150235,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.927461,1.000000,0.626943,0.193437,0.094991,0.072539,0.043178,0.053541,0.093264,0.189983,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87548,0.807018,0.494737,0.536842,0.529825,0.491228,0.484211,0.456140,0.396491,0.284211,0.136842,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87549,0.718333,0.605000,0.486667,0.361667,0.231667,0.120000,0.051667,0.001667,0.000000,0.013333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87550,0.906122,0.624490,0.595918,0.575510,0.530612,0.481633,0.444898,0.387755,0.322449,0.191837,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87551,0.858228,0.645570,0.845570,0.248101,0.167089,0.131646,0.121519,0.121519,0.118987,0.103797,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
87552,0.901506,0.845886,0.800695,0.748552,0.687138,0.599073,0.512167,0.427578,0.395133,0.402086,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [4]:
mitbihTestdf

,1.000000000000000000e+00,7.582644820213317871e-01,1.115702465176582336e-01,0.000000000000000000e+00,8.057851344347000122e-02,7.851240038871765137e-02,6.611569970846176147e-02,4.958677664399147034e-02,4.752065986394882202e-02,3.512396663427352905e-02,...,0.000000000000000000e+00.56,0.000000000000000000e+00.57,0.000000000000000000e+00.58,0.000000000000000000e+00.59,0.000000000000000000e+00.60,0.000000000000000000e+00.61,0.000000000000000000e+00.62,0.000000000000000000e+00.63,0.000000000000000000e+00.64,0.000000000000000000e+00.65
0,0.908425,0.783883,0.531136,0.362637,0.366300,0.344322,0.333333,0.307692,0.296703,0.300366,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.730088,0.212389,0.000000,0.119469,0.101770,0.101770,0.110619,0.123894,0.115044,0.132743,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.000000,0.910417,0.681250,0.472917,0.229167,0.068750,0.000000,0.004167,0.014583,0.054167,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.570470,0.399329,0.238255,0.147651,0.000000,0.003356,0.040268,0.080537,0.070470,0.090604,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.000000,0.923664,0.656489,0.195929,0.111959,0.175573,0.122137,0.050891,0.035623,0.055980,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21886,0.928736,0.871264,0.804598,0.742529,0.650575,0.535632,0.394253,0.250575,0.140230,0.102299,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21887,0.802691,0.692078,0.587444,0.446936,0.318386,0.189836,0.118087,0.077728,0.112108,0.152466,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21888,1.000000,0.967359,0.620178,0.347181,0.139466,0.089021,0.103858,0.100890,0.106825,0.100890,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21889,0.984127,0.567460,0.607143,0.583333,0.607143,0.575397,0.575397,0.488095,0.392857,0.238095,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
21890,0.973970,0.913232,0.865510,0.823210,0.746204,0.642082,0.547722,0.426247,0.325380,0.279826,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [5]:
ptbdbNormaldf

,1.000000000000000000e+00,9.003241658210754395e-01,3.585899472236633301e-01,5.145867168903350830e-02,4.659643396735191345e-02,1.268233358860015869e-01,1.333063244819641113e-01,1.191247999668121338e-01,1.106158867478370667e-01,1.130470037460327148e-01,...,0.000000000000000000e+00.56,0.000000000000000000e+00.57,0.000000000000000000e+00.58,0.000000000000000000e+00.59,0.000000000000000000e+00.60,0.000000000000000000e+00.61,0.000000000000000000e+00.62,0.000000000000000000e+00.63,0.000000000000000000e+00.64,0.000000000000000000e+00.65
0,1.000000,0.794681,0.375387,0.116883,0.000000,0.171923,0.283859,0.293754,0.325912,0.345083,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.909029,0.791482,0.423169,0.186712,0.000000,0.007836,0.063032,0.077002,0.074957,0.077342,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.000000,0.478893,0.056760,0.064176,0.081289,0.072732,0.055619,0.048774,0.054478,0.041643,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.000000,0.867238,0.201360,0.099349,0.141336,0.120934,0.108516,0.096393,0.093436,0.100828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.948983,0.505265,0.004176,0.022513,0.059550,0.107298,0.110385,0.111293,0.116558,0.118192,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4040,1.000000,0.929586,0.503550,0.293491,0.169822,0.159763,0.130769,0.125444,0.137278,0.111243,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4041,1.000000,0.637579,0.154837,0.061983,0.088965,0.083374,0.065143,0.057365,0.060039,0.060039,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4042,1.000000,0.872574,0.465071,0.232212,0.126132,0.155886,0.174644,0.190168,0.203752,0.168823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4043,0.915983,0.529373,0.288406,0.144536,0.171802,0.180669,0.177566,0.176458,0.178896,0.180448,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4044,1.000000,0.838643,0.390567,0.191146,0.033513,0.055854,0.129086,0.147290,0.155151,0.165494,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
ptbdbAbnormaldf

,9.322328567504882812e-01,8.696785569190979004e-01,8.861859440803527832e-01,9.296264052391052246e-01,9.087749719619750977e-01,9.339704513549804688e-01,8.010425567626953125e-01,7.497828006744384766e-01,6.872285008430480957e-01,6.350998878479003906e-01,...,0.000000000000000000e+00.117,0.000000000000000000e+00.118,0.000000000000000000e+00.119,0.000000000000000000e+00.120,0.000000000000000000e+00.121,0.000000000000000000e+00.122,0.000000000000000000e+00.123,0.000000000000000000e+00.124,0.000000000000000000e+00.125,1.000000000000000000e+00.1
0,1.000000,0.606941,0.384181,0.254237,0.223567,0.276836,0.253430,0.184826,0.153349,0.121872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.000000,0.951613,0.923963,0.853303,0.791859,0.734255,0.672043,0.685100,0.670507,0.667435,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.977819,0.899261,0.230129,0.032348,0.142329,0.223660,0.328096,0.367837,0.381701,0.389094,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.935618,0.801661,0.805815,1.000000,0.722741,0.480789,0.454829,0.319834,0.266874,0.308411,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.925265,0.433352,0.073620,0.079197,0.136643,0.182934,0.182934,0.182376,0.196877,0.203569,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10500,0.981409,1.000000,0.559171,0.287093,0.196639,0.204862,0.215946,0.243833,0.242760,0.250268,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10501,0.906250,0.922379,0.878024,0.810484,0.712702,0.667339,0.608871,0.527218,0.480847,0.442540,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10502,1.000000,0.867971,0.674122,0.470332,0.296987,0.169307,0.077664,0.081392,0.074868,0.089779,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10503,1.000000,0.984672,0.658888,0.556394,0.446809,0.395790,0.315260,0.276367,0.261039,0.258522,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10504,0.997886,0.700317,0.464059,0.318182,0.233615,0.184989,0.124207,0.082981,0.087738,0.063953,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Transfer Learning Goal
- To train a model on mitbih data
- Test the model on mitbih test data
- Remove last two layers and add two layers at the end for fine tuning as per paper
- Train these last two layers only and check accuracy on ptbdb data

### Pre processing data
- One hot encoding is also needed for 5 classes

In [7]:
m,n = mitbihTraindf.shape
print(m,n)

87553 188

In [8]:
train_data = mitbihTraindf.to_numpy()
train_data = train_data.T

In [9]:
train_data

array([[0.96011394, 1.        , 0.92541438, ..., 0.90612245, 0.85822785,
        0.90150636],
       [0.86324787, 0.65945947, 0.66574585, ..., 0.62448978, 0.64556962,
        0.84588647],
       [0.46153846, 0.18648648, 0.54143649, ..., 0.59591836, 0.84556961,
        0.80069524],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 4.        , 4.        ,
        4.        ]])

#### Now our row has the labels
##### Classes: ['N': 0, 'S': 1, 'V': 2, 'F': 3, 'Q': 4]

In [10]:
trainY = train_data[-1]
print("Size : 1 x",len(trainY))
trainY

Size : 1 x 87553

array([0., 0., 0., ..., 4., 4., 4.])

In [11]:
trainX = train_data[:n-1]
print("Size : ",len(trainX),"x",len(trainX[0]))
trainX

Size :  187 x 87553

array([[0.96011394, 1.        , 0.92541438, ..., 0.90612245, 0.85822785,
        0.90150636],
       [0.86324787, 0.65945947, 0.66574585, ..., 0.62448978, 0.64556962,
        0.84588647],
       [0.46153846, 0.18648648, 0.54143649, ..., 0.59591836, 0.84556961,
        0.80069524],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

#### So now we have proper data split
- Each column must be passed as input, i.e. 187 inputs are for one run/test case

### Preprocessing test data as well

In [12]:
m,n = mitbihTestdf.shape
print(m,n)

21891 188

In [13]:
test_data = mitbihTestdf.to_numpy()
test_data = test_data.T
print(test_data)
print(n,"x",m)

[[0.90842491 0.73008847 1.         ... 1.         0.98412699 0.97396964]
 [0.7838828  0.21238938 0.91041666 ... 0.96735907 0.5674603  0.91323209]
 [0.53113556 0.         0.68124998 ... 0.62017804 0.60714287 0.86550975]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 4.         4.         4.        ]]
188 x 21891

In [14]:
testY = test_data[-1]
print("Size : 1 x ",len(testY))
testY

Size : 1 x  21891

array([0., 0., 0., ..., 4., 4., 4.])

In [15]:
testX = test_data[0:n-1]
print("Size : ",len(testX),"x",len(testX[0]))
testX

Size :  187 x 21891

array([[0.90842491, 0.73008847, 1.        , ..., 1.        , 0.98412699,
        0.97396964],
       [0.7838828 , 0.21238938, 0.91041666, ..., 0.96735907, 0.5674603 ,
        0.91323209],
       [0.53113556, 0.        , 0.68124998, ..., 0.62017804, 0.60714287,
        0.86550975],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

### MLP Architecture (187 -> 512 -> 256 -> 128 -> 64 -> 32 -> 16 -> 5)
- We need last two layer as configurable and removable so previous layers must encode enough features
- Input layer is 187 since 187 features, 
- Output layer is 5 since 5 classes
- Let's keep 5 hiddenlayers with last two removable
- So (187 -> 512 -> 256 -> 128 -> 64 -> 32 -> 16 -> 5)
- We can provide 64 features to our ptbdb dataset and train a 8 -> 2 layers next for fine tuning

### Init Parameters

In [16]:
#Using He Init with ReLU
def init_params():
    W1 = np.random.randn(512,187)*np.sqrt(2/187)
    b1 = np.zeros((512,1))
    W2 = np.random.randn(256,512)*np.sqrt(2/512)
    b2 = np.zeros((256,1))
    W3 = np.random.randn(128,256)*np.sqrt(2/256)
    b3 = np.zeros((128,1))
    W4 = np.random.randn(64,128)*np.sqrt(2/128)
    b4 = np.zeros((64,1))
    W5 = np.random.randn(32,64)*np.sqrt(2/64)
    b5 = np.zeros((32,1))
    W6 = np.random.randn(16,32)*np.sqrt(2/32)
    b6 = np.zeros((16,1))
    W7 = np.random.randn(5,16)*np.sqrt(2/16)
    b7 = np.zeros((5,1))
    
    wArr = [W1,W2,W3,W4,W5,W6,W7]
    bArr = [b1,b2,b3,b4,b5,b6,b7]
    
    return wArr,bArr

In [17]:
init_params()

([array([[-0.09292099, -0.05958299, -0.01890939, ...,  0.18373212,
          -0.02194029,  0.02667523],
         [ 0.07448798, -0.13763199, -0.17194299, ...,  0.06724868,
           0.02291123, -0.09707481],
         [-0.05980745,  0.06764881,  0.12806415, ..., -0.00224856,
          -0.09915808,  0.10569533],
         ...,
         [ 0.11087726, -0.03776509,  0.02168396, ...,  0.04293583,
           0.04241729,  0.07338053],
         [ 0.06609759, -0.09183552,  0.0586907 , ...,  0.01480796,
          -0.08323748,  0.18756191],
         [ 0.22009895,  0.0017983 ,  0.02576369, ...,  0.15609642,
          -0.0082159 , -0.00759523]]),
  array([[-3.37992434e-02, -3.64958827e-02, -3.23917908e-02, ...,
          -8.13024886e-02,  1.24726331e-01,  9.24394249e-02],
         [-9.30231641e-03, -1.48916129e-02, -2.20560835e-02, ...,
          -7.88080027e-02,  5.83482793e-02, -1.68233512e-04],
         [-5.86025103e-02, -1.63071384e-02, -2.94438393e-02, ...,
          -1.79277004e-02, -7.41363829e-02,  2.24776785e-02],
         ...,
         [ 3.34721364e-02, -1.11827820e-02, -5.90619556e-02, ...,
          -2.79268133e-02, -6.86422678e-02,  1.68279643e-01],
         [ 1.00752849e-01,  8.50749201e-02, -6.14290378e-02, ...,
          -7.69512505e-02, -3.95770690e-02, -2.01827377e-02],
         [ 4.25370617e-02,  7.12995154e-02, -6.04995386e-02, ...,
          -9.94873173e-02, -9.80381289e-02, -2.09102465e-02]]),
  array([[-0.13065636, -0.05048901,  0.13706511, ..., -0.00446706,
          -0.12989245, -0.07443071],
         [-0.15950596, -0.03437455,  0.15664765, ..., -0.06863529,
          -0.08066378,  0.03473634],
         [-0.03714283, -0.03089482,  0.10053729, ..., -0.0057709 ,
           0.09958046, -0.16330512],
         ...,
         [ 0.05679582,  0.01596833, -0.02180252, ..., -0.04811187,
          -0.02005758,  0.01113973],
         [-0.09516417, -0.1195924 , -0.11054893, ...,  0.12729064,
           0.15481601,  0.07299335],
         [-0.0062548 , -0.02497083,  0.01884045, ..., -0.02027734,
           0.06015761, -0.03057456]]),
  array([[-0.03655076,  0.01807329, -0.19675448, ..., -0.13583149,
           0.04048188, -0.17449106],
         [-0.22343401, -0.06142806,  0.12918951, ..., -0.02099159,
           0.08220533, -0.02477527],
         [ 0.12424151,  0.12017663,  0.13856401, ...,  0.03998908,
          -0.12724968, -0.24019576],
         ...,
         [-0.17387378, -0.06661035,  0.03704177, ...,  0.15819122,
           0.0188578 ,  0.2448359 ],
         [ 0.02737033,  0.09062373,  0.27355968, ..., -0.07602378,
          -0.16836515,  0.27926776],
         [ 0.22750643, -0.02199054,  0.04977136, ..., -0.02220303,
           0.2842693 , -0.17643978]]),
  array([[-0.16257782,  0.12833408, -0.06565285, ..., -0.17600415,
          -0.01167058, -0.09936875],
         [-0.27088549, -0.24011851,  0.38923163, ..., -0.15624577,
           0.13165623, -0.10721309],
         [ 0.02479741, -0.01410082,  0.12281096, ...,  0.01416809,
          -0.06474831, -0.02671729],
         ...,
         [-0.00519554, -0.08925525, -0.19397503, ...,  0.19590049,
          -0.16347114,  0.10149928],
         [ 0.04904552,  0.05727744,  0.22628045, ...,  0.20742299,
          -0.22029192, -0.04867965],
         [ 0.12947888,  0.03497366,  0.2223514 , ..., -0.01878875,
          -0.29445703, -0.17453039]]),
  array([[ 1.07397067e-02,  1.07233571e-01,  2.26253056e-01,
          -1.22581926e-02,  2.12745813e-01, -2.29320539e-01,
           5.13626897e-03, -1.89835940e-01,  3.30477320e-02,
           1.77961883e-02, -3.27357529e-01,  1.16839847e-01,
           2.23839507e-01,  3.22800309e-01,  5.39286944e-02,
          -4.92908790e-02, -1.35621039e-01, -1.25897017e-01,
           5.73560047e-01, -2.96899188e-01, -1.18730584e-01,
          -1.74799381e-01,  1.43103832e-01, -3.37768982e-01,
          -1.22225966e-02,  2.03937958e-01, -1.48643955e-01,
          -7.40391639e-02,  4.70962419e-02,  2.77040183e-01,
          -2.15992055e-01,  9.70749164e-02],
         [ 3.51866231e-01, -9.76983515e-04, -1.62200092e-01,
          -4.37495651e-02, -2.87743695e-01, -2.61677708e-02,
          -4.09180630e-01,  7.17037546e-02, -2.76680075e-01,
           4.17054331e-01, -8.81295276e-02,  5.38693352e-01,
           1.40850200e-01, -7.88980058e-02,  2.25622170e-01,
           2.07507417e-01,  2.16350176e-01, -6.31035024e-02,
           4.83478163e-01,  7.36848817e-02, -1.52437151e-01,
          -3.73547392e-01, -1.03516166e-01,  5.09901388e-01,
           2.03550154e-01, -2.57778339e-01, -1.37346033e-01,
          -3.39791303e-01, -8.88830754e-02,  2.51925240e-01,
           2.82484879e-01,  3.99199777e-03],
         [-3.45028307e-01, -2.99583551e-01,  8.57788139e-02,
          -1.18345724e-01, -3.76808494e-01,  2.51332275e-01,
          -1.37965394e-01, -4.33380641e-02,  1.79753649e-01,
          -1.30224557e-01, -1.32237348e-01,  1.24233283e-02,
           2.30771093e-01,  6.28446918e-02,  1.78951524e-01,
          -3.04757361e-01, -5.27171367e-02,  3.97984083e-01,
           4.58317286e-01,  3.80599781e-01,  2.91899019e-01,
           6.05646115e-02,  2.61267747e-01,  2.90351669e-01,
          -3.01699034e-01, -1.04198770e-01,  3.15401974e-02,
          -3.45690936e-01,  5.09575733e-01,  1.62399328e-01,
          -1.14617710e-01,  8.47112849e-02],
         [ 2.30408623e-01,  2.72923837e-01,  7.06299324e-03,
          -1.17940155e-01, -3.94040426e-01, -1.06009016e-01,
          -3.28001653e-02, -8.37484074e-03, -3.38698967e-01,
           1.87389886e-01, -2.13705702e-01, -4.87144053e-01,
          -4.58551759e-01,  1.22267611e-01, -2.34108929e-01,
          -3.07216561e-01, -3.69199937e-01, -3.08316535e-01,
          -4.24309993e-01,  1.42089507e-01,  2.01177257e-01,
          -1.93233291e-01,  2.25461777e-01,  2.40784136e-01,
          -1.93086220e-01,  1.78609010e-01, -6.76655391e-02,
           2.95507404e-01, -1.03057529e-01,  6.75022892e-02,
           1.42143641e-01, -1.01534845e-01],
         [ 8.13788879e-02, -4.91733184e-01, -1.81819792e-01,
           2.71347371e-01,  2.09043544e-01,  3.97767772e-01,
          -4.14206682e-01, -1.44242926e-01,  3.89804431e-01,
           1.46596827e-01, -1.52751279e-01,  9.75275568e-02,
           5.46875533e-01, -2.77150999e-01,  4.09981878e-02,
           2.67824079e-01,  2.92526046e-02, -2.39993503e-01,
          -2.15664401e-01, -3.91964066e-01,  6.21834157e-02,
          -1.07624412e-01,  6.47045784e-02, -3.57715324e-01,
          -8.10485571e-02,  4.51927540e-01,  1.13681287e-01,
          -2.81562119e-01,  6.64413427e-02, -9.18127695e-02,
           3.01049230e-01, -6.27632234e-02],
         [-3.26058587e-01,  9.58644333e-02,  1.94634829e-01,
           2.03414154e-01,  2.43471662e-01, -1.14420306e-02,
          -3.99827260e-02,  1.55383803e-01, -1.18248968e-01,
           8.66319061e-02,  1.12424747e-01, -2.93058188e-01,
          -2.83374250e-01,  1.10195219e-02, -1.87273103e-01,
           3.12715604e-01,  1.33613669e-01,  3.39640314e-01,
           1.96949960e-01,  8.49998377e-02, -3.39892377e-01,
          -1.07725017e-01,  2.37225667e-01,  8.18558122e-02,
           6.99092960e-02,  4.42653833e-01,  1.37729950e-01,
          -6.06420870e-02,  1.78874519e-01,  3.38275977e-01,
          -2.13429829e-02, -4.30850006e-01],
         [ 9.23002925e-02, -2.54179663e-01, -5.13239350e-02,
           2.21004058e-01,  1.17576944e-01,  2.07277653e-01,
           1.38827720e-01, -1.83869886e-01, -2.92730176e-01,
          -2.78376670e-01, -2.52222457e-01, -3.33994149e-01,
           1.03799337e-01,  7.43858268e-02,  2.95431946e-01,
          -3.29270599e-01, -1.69595939e-01,  2.09421962e-01,
          -4.77929757e-02,  1.70054439e-01,  3.43626777e-01,
           1.23539811e-01, -1.12510082e-01, -4.09585380e-02,
           4.11348396e-02,  4.02531567e-02,  2.83205133e-01,
           3.96333557e-01,  2.68268898e-02, -2.78343774e-01,
           2.09119814e-01, -6.59177207e-04],
         [ 4.22047224e-02, -1.03248909e-01, -3.19485110e-01,
          -1.22101570e-01,  6.11587997e-02,  6.78632407e-01,
          -2.26694456e-01, -1.59952097e-01,  4.37154585e-02,
           3.19753044e-01,  3.14422204e-02, -5.72598803e-02,
          -2.73009649e-03,  2.46052212e-01, -2.59759049e-01,
           2.32029398e-01,  1.18700830e-01,  3.47915411e-01,
          -2.60557057e-01,  7.45282723e-03,  1.43708015e-01,
          -5.76981111e-02, -3.01411354e-01,  1.93338387e-01,
          -2.18250762e-01,  1.48752730e-02, -3.08639965e-01,
           1.58471537e-01,  3.59425506e-01,  8.69846617e-02,
          -3.79220610e-02,  1.03157702e-01],
         [-2.03416249e-01,  1.72357632e-01, -3.57539126e-01,
           3.34942575e-01, -3.03002635e-01,  1.05030095e-01,
           1.33757952e-01, -1.53128853e-01, -1.46911328e-01,
           1.47666818e-01,  6.01196386e-02,  1.64624066e-01,
          -2.04071721e-01,  2.95121267e-01, -2.58591850e-01,
          -4.24763813e-02,  8.85223300e-03, -8.22936603e-02,
           1.56239109e-01,  8.28641951e-03,  6.52704461e-02,
          -3.45089032e-01,  4.91495505e-01,  2.66510164e-01,
           1.68352630e-01, -4.58432943e-02,  3.24891258e-01,
           1.27159288e-01,  2.05748790e-01,  2.37172525e-01,
          -1.96186442e-02, -5.95838369e-03],
         [ 2.73629676e-01, -3.64296748e-01, -1.00369915e-01,
           6.87636485e-02, -5.58586883e-02,  1.61370935e-02,
          -2.18930398e-01,  1.72556964e-01,  3.54645071e-01,
          -1.91883287e-01,  1.95206410e-01, -2.20711975e-01,
          -7.27692520e-03, -1.24707632e-02, -5.16532855e-01,
           3.37116243e-02, -3.36529229e-01,  1.09814029e-01,
           1.53258203e-01,  3.50065412e-02, -3.45742236e-01,
           2.07225763e-03, -4.11457565e-01, -3.39089898e-01,
           2.96230780e-01,  2.18795491e-01,  4.05173592e-01,
          -9.71260539e-02,  3.03820703e-01,  2.45544356e-01,
          -5.98777690e-02, -4.44531392e-01],
         [-2.78063832e-01,  3.55436896e-01,  7.54914392e-01,
           1.33733288e-01, -1.10876495e-01,  1.32133977e-01,
           7.14229214e-02,  1.08646002e-01,  5.73531006e-02,
          -3.34015901e-01,  1.32277452e-02,  3.07394743e-01,
           1.24741508e-01,  5.83834014e-02,  3.61925308e-01,
          -3.35043486e-01,  3.81591134e-01, -1.25771894e-01,
           1.01472591e-01, -2.08910347e-02, -5.82851537e-01,
           4.47646698e-02,  1.30666552e-01,  6.75612007e-02,
           2.90200071e-01,  4.71191312e-01,  3.63969755e-02,
           1.47111434e-01, -1.98471751e-01, -5.54282489e-02,
           1.17784523e-02, -2.29795541e-01],
         [-1.58206923e-01,  1.20643284e-01, -2.83412177e-01,
          -1.42316897e-01,  9.93918843e-02, -1.46545812e-01,
          -4.91444351e-01,  3.85597158e-01,  7.04398132e-02,
           2.00554776e-01,  3.91678750e-01,  1.12693238e-01,
          -1.60953043e-01, -2.47910080e-01, -7.03641017e-02,
           5.84104593e-02,  4.22119525e-02,  2.78942180e-02,
           3.83995006e-02,  1.28120322e-01,  2.52509909e-01,
           4.22744801e-02,  2.70681473e-01, -1.65624590e-01,
          -7.91344981e-02,  5.90783189e-01,  6.93829773e-02,
           1.62090313e-02, -2.28617297e-02,  9.94068225e-02,
          -1.78423321e-01,  3.32607915e-01],
         [-1.78512053e-01,  4.25136077e-01, -5.57687549e-01,
           2.13882953e-01,  1.55613963e-01,  3.09153620e-01,
          -2.20324225e-01, -1.57044477e-02,  1.81482020e-02,
          -5.33129597e-02, -2.21232228e-02, -1.59136854e-01,
           5.53868363e-01,  8.91391971e-02, -6.91120887e-02,
           1.24279346e-01, -5.87117763e-02, -3.76568728e-01,
          -1.63865168e-01, -1.84168639e-01,  2.91548289e-02,
           5.04091366e-01, -1.16840350e-01, -6.00815762e-02,
           7.49465918e-01,  6.20413675e-02, -5.99265388e-02,
           2.37118479e-01,  3.65231682e-01,  3.28989140e-01,
          -1.44289326e-01, -1.20897676e-01],
         [ 3.50273323e-01,  1.20918348e-01, -5.73310386e-02,
           3.47465465e-02,  1.46565952e-01, -3.93288822e-01,
           1.01514139e-01, -2.75496513e-01,  1.81710574e-01,
          -1.64680671e-01, -3.59640791e-01, -2.74965374e-01,
          -3.46984659e-01, -1.60333445e-03, -2.39022156e-01,
           3.59668661e-01, -9.54656138e-02, -3.88748035e-01,
          -8.16932023e-02, -7.29244940e-02, -1.40087123e-01,
          -4.35620201e-01, -1.16759375e-01, -8.57111560e-02,
           2.74204067e-01, -1.87052430e-01,  1.80458219e-01,
           5.74307484e-02,  3.79279382e-02, -1.15253060e-01,
          -2.87679248e-01, -6.69100249e-02],
         [-3.62155092e-01,  1.99329177e-01,  1.80533716e-01,
          -1.69281138e-01, -4.44267254e-01,  1.64166985e-02,
           8.92713571e-02, -2.78625053e-01,  4.24885414e-03,
          -1.04077743e-01,  9.75340688e-02,  1.00254877e-01,
           5.69397463e-02,  1.36222324e-01, -1.89326744e-01,
          -3.42513847e-01, -1.56930459e-01,  8.51368025e-02,
           1.15438223e-02,  3.56426717e-01,  1.31446936e-01,
           4.24232471e-02,  4.69773889e-01,  5.49546054e-02,
          -4.03093232e-01,  1.37965207e-01,  2.54132610e-01,
          -6.51709305e-02,  2.16342413e-02, -6.48623371e-02,
          -4.17525518e-01, -3.27957282e-01],
         [-1.18121040e-01,  1.12159741e-01,  2.39496012e-01,
           4.05620685e-02, -1.25998658e-01,  2.26213424e-01,
           1.62732242e-01, -1.38092968e-01,  3.19601250e-01,
           3.58347570e-01, -6.29020054e-02, -1.13726175e-01,
          -3.80889122e-01,  2.44355788e-02,  1.24365370e-01,
           2.46216529e-01, -6.21845945e-01,  1.07997473e-01,
          -6.71212739e-01,  1.39213173e-01, -3.11092989e-01,
          -6.18744032e-03, -1.26868223e-01, -1.82254599e-01,
          -3.00282898e-01, -2.31387440e-01,  5.79118407e-02,
           9.61405214e-02,  2.72003185e-01, -1.17816752e-01,
          -4.20998362e-01,  1.33909387e-02]]),
  array([[ 1.15368721e-01,  6.62189152e-02,  1.03181815e-01,
          -2.04302891e-01, -1.06519403e-02,  2.88789378e-01,
          -9.16581264e-01,  2.30688682e-01,  2.32541258e-01,
           1.04381683e-01, -2.41378240e-01,  9.84625567e-01,
           1.87027492e-01, -2.68511166e-01,  4.32550588e-01,
          -6.39498867e-01],
         [-2.07004870e-01, -4.97865340e-01,  1.35455247e-01,
          -1.76851677e-02,  6.88627729e-02,  2.50559545e-01,
           3.70288447e-01, -2.66582990e-01,  3.64337622e-02,
          -6.64473101e-01,  3.76153176e-01, -3.24994650e-02,
          -1.91684198e-01,  2.16227193e-01, -8.67932688e-02,
          -3.37620101e-01],
         [ 4.64149892e-02,  6.29644567e-01, -1.70338865e-01,
           1.89438948e-01,  7.84781723e-01,  7.88472370e-01,
          -1.23796372e-01, -1.06350388e-03,  1.92237968e-01,
           4.50904783e-01,  1.47003203e-01,  1.28475557e-01,
          -1.03870271e-01, -1.20884666e-01, -3.09756756e-01,
          -3.26837716e-01],
         [-3.70289899e-01,  8.72744165e-02, -6.30524638e-01,
           4.69678770e-02, -9.43165370e-02,  1.00977254e-01,
           2.60592729e-01, -3.64919914e-01, -3.35740492e-01,
           3.07059005e-01, -9.29121311e-02, -4.58636993e-01,
          -1.86229501e-01,  2.79438220e-01, -3.21961788e-02,
           2.49453108e-01],
         [-5.78772093e-01,  3.86009003e-02,  1.01888050e-01,
           2.35322126e-01, -1.08243361e-01,  2.34458532e-01,
          -4.90598990e-04, -2.92753964e-01,  3.68819655e-01,
           4.10060420e-01,  1.10769985e-01,  1.04916572e-01,
           2.37666617e-01, -1.40449197e-01, -1.20931443e-01,
           3.65875215e-01]])],
 [array([[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],

### Utility Functions

In [18]:
def ReLU(Z):
    return np.maximum(Z,0)

def derivative_ReLU(Z):
    return Z>0

def softmax(Z):
    expZ = np.exp(Z-np.max(Z,axis = 0,keepdims = True))
    return expZ/np.sum(expZ,axis =0 ,keepdims = True)

def one_hot(Y):
    #We need 5 classes
    size = Y.size
    one_hot_Y = np.zeros((5,size))
    for index,val in enumerate(Y):
        one_hot_Y[int(val)][index]=1
    
    return one_hot_Y

In [19]:
one_hot(trainY)

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 1., 1.]])

### Main Functions

In [20]:
def forward_pass(X,wArr,bArr):
    
    #Number of Layers
    n = len(wArr)
    
    activationVal = X
    zArr = []
    aArr = []
    for i in range(n):
        
        zArr.append(wArr[i].dot(activationVal) + bArr[i])
        if i!=n-1:
            activationVal = ReLU(zArr[-1])
            aArr.append(activationVal)
        else:
            activationVal = softmax(zArr[-1])
            aArr.append(activationVal)
            
#     for index,arr in enumerate(aArr):
#         print(index," : ",len(arr),len(arr[0]))
        
    return zArr,aArr

In [21]:
def backward_pass(X,Y,zArr,aArr,wArr):
    
    m = Y.size
    
    #Number of Layers
    n = len(wArr)
    
    dZArr,dWArr,dbArr = [],[],[]
    
    one_hot_Y = one_hot(Y)
    
    for i in range(n):
        
        if i==0:
            dZArr.append(aArr[-1] - one_hot_Y)
        else:
            dZArr.append(wArr[n-i].T.dot(dZArr[-1]) * derivative_ReLU(zArr[n-i-1]))
        
        if i==n-1:
            dWArr.append(1/m * dZArr[-1].dot(X.T))
        else:
            dWArr.append(1/m * dZArr[-1].dot(aArr[n-i-2].T))
            
        dbArr.append(1/m * np.sum(dZArr[-1], axis = 1, keepdims = True))
            
    return dWArr[::-1],dbArr[::-1]

In [22]:
def update_params(alpha,dWArr,dbArr,wArr,bArr):
    
    #Number of Layers
    n = len(wArr)
    
    for i in range(n):
#         print("Debug w : ",len(wArr[i]),"x",len(wArr[i][0]),"Debug dw : ",len(dWArr[i]),"x",len(dWArr[i][0]))
        wArr[i] -= alpha * dWArr[i]
        bArr[i] -= alpha * dbArr[i]
        
    return wArr,bArr

### Driver Function

In [23]:
def get_prediction(A):
    return np.argmax(A,0)

def get_accuracy(prediction,Y):
    #The Y values we get are letters
    
    return np.sum(prediction==Y)/len(Y)

def sgd(X,Y,alpha,epochs):
    
    wArr,bArr = init_params()
    batch_size = 1000
        
    for epoch_cnt in range(epochs):
        
        shuffled_indices = np.random.permutation(Y.size)
        X_shuffled = X[:, shuffled_indices]
        Y_shuffled = Y[shuffled_indices]
    
        for start in range(0,Y.size,batch_size):

            end = start + batch_size

            X_batch = X_shuffled[:,start:end]
            Y_batch = Y_shuffled[start:end]

            #Perform Forward Pass
            zArr, aArr = forward_pass(X_batch,wArr,bArr)

            #Perform Backward Pass
            dWArr,dbArr = backward_pass(X_batch,Y_batch,zArr,aArr,wArr)

            #Update Parameters
            wArr,bArr = update_params(alpha,dWArr,dbArr,wArr,bArr)
            
        print("Epoch : ",epoch_cnt)
        prediction = get_prediction(aArr[-1])
        print(get_accuracy(prediction,Y_batch))
            
    return wArr,bArr

In [24]:
wArr,bArr = sgd(trainX,trainY,0.01,50)

Epoch :  0
0.8137432188065099
Epoch :  1
0.8191681735985533
Epoch :  2
0.8589511754068716
Epoch :  3
0.9005424954792043
Epoch :  4
0.8969258589511754
Epoch :  5
0.8933092224231465
Epoch :  6
0.9095840867992767
Epoch :  7
0.9294755877034359
Epoch :  8
0.9240506329113924
Epoch :  9
0.918625678119349
Epoch :  10
0.9421338155515371
Epoch :  11
0.9367088607594937
Epoch :  12
0.9385171790235082
Epoch :  13
0.9222423146473779
Epoch :  14
0.945750452079566
Epoch :  15
0.9403254972875226
Epoch :  16
0.9529837251356239
Epoch :  17
0.9403254972875226
Epoch :  18
0.9385171790235082
Epoch :  19
0.9204339963833634
Epoch :  20
0.9511754068716094
Epoch :  21
0.9475587703435805
Epoch :  22
0.9638336347197106
Epoch :  23
0.945750452079566
Epoch :  24
0.9421338155515371
Epoch :  25
0.9620253164556962
Epoch :  26
0.9620253164556962
Epoch :  27
0.9602169981916817
Epoch :  28
0.9439421338155516
Epoch :  29
0.9529837251356239
Epoch :  30
0.9584086799276673
Epoch :  31
0.9584086799276673
Epoch :  32
0.976491862567812
Epoch :  33
0.9421338155515371
Epoch :  34
0.9638336347197106
Epoch :  35
0.9584086799276673
Epoch :  36
0.9638336347197106
Epoch :  37
0.9602169981916817
Epoch :  38
0.9674502712477396
Epoch :  39
0.9620253164556962
Epoch :  40
0.972875226039783
Epoch :  41
0.9656419529837251
Epoch :  42
0.9656419529837251
Epoch :  43
0.9638336347197106
Epoch :  44
0.9638336347197106
Epoch :  45
0.9656419529837251
Epoch :  46
0.9529837251356239
Epoch :  47
0.9638336347197106
Epoch :  48
0.9656419529837251
Epoch :  49
0.969258589511754

### 96.925 % Accuracy !!!

In [25]:
def make_prediction(X,wArr,bArr):
    
    #Perform Forward Pass
    _,aArr = forward_pass(X,wArr,bArr)
    A = aArr[-1]
    
    return get_prediction(A)

In [26]:
predictions = make_prediction(testX,wArr,bArr)
print(predictions.size,predictions,testY)
get_accuracy(predictions,testY)

21891 [0 0 0 ... 4 4 4] [0. 0. 0. ... 4. 4. 4.]

0.965556621442602

### 96.55 % Accuracy !!!
- No signs of overfitting

### TRANSFER LEARNING IMPLEMENTATION
- Use the earlier layers till 32, so 32 features of ECG are not getting trained again
- The last two layers of 8-> 2 need to be added, where 2 is the output layer