## Letter Classification

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [2]:
df = pd.read_csv("letter-recognition.csv")

In [3]:
df.head(10)

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
5,S,4,11,5,8,3,8,8,6,9,5,6,6,0,8,9,7
6,B,4,2,5,4,4,8,7,6,6,7,6,6,2,8,7,10
7,A,1,1,3,2,1,8,2,2,2,8,2,8,1,6,2,7
8,J,2,2,4,4,2,10,6,2,6,12,4,8,1,6,1,7
9,M,11,15,13,9,7,13,2,6,2,12,1,9,8,1,1,8

In [4]:
df.tail(10)

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
19990,W,3,8,5,6,5,11,11,2,2,5,8,7,7,12,1,7
19991,O,4,3,5,4,2,7,6,8,8,6,5,7,3,8,4,8
19992,E,4,9,5,6,3,5,9,2,10,10,8,9,2,8,5,5
19993,J,2,11,3,8,2,15,4,4,5,13,1,8,0,7,0,8
19994,T,5,8,7,7,7,7,9,4,8,7,7,8,3,10,8,6
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [5]:
m,n = df.shape

In [6]:
print(m,n)

20000 17

In [7]:
df.info

<bound method DataFrame.info of       letter  xbox   ybox   width   height  onpix   xbar   ybar   x2bar  \
0          T      2      8       3       5       1      8     13      0
1          I      5     12       3       7       2     10      5      5
2          D      4     11       6       8       6     10      6      2
3          N      7     11       6       6       3      5      9      4
4          G      2      1       3       1       1      8      6      6
...      ...    ...    ...     ...     ...     ...    ...    ...    ...
19995      D      2      2       3       3       2      7      7      7
19996      C      7     10       8       8       4      4      8      6
19997      T      6      9       6       7       5      6     11      3
19998      S      2      3       4       2       1      8      7      2
19999      A      4      9       6       6       2      9      5      3

       y2bar   xybar   x2ybar  xy2bar  xedge   xedgey  yedge   yedgex
0           6       6      10       8       0       8       0       8
1           4      13       3       9       2       8       4      10
2           6      10       3       7       3       7       3       9
3           6       4       4      10       6      10       2       8
4           6       6       5       9       1       7       5      10
...       ...     ...     ...     ...     ...     ...     ...     ...
19995       6       6       6       4       2       8       3       7
19996       9      12       9      13       2       9       3       7
19997       7      11       9       5       2      12       2       4
19998       6      10       6       8       1       9       5       8
19999       1       8       1       8       2       7       2       8

[20000 rows x 17 columns]>

#### So rather than actual pixel image we have 16 features for each image

In [8]:
data = df.to_numpy()
data

array([['T', 2, 8, ..., 8, 0, 8],
       ['I', 5, 12, ..., 8, 4, 10],
       ['D', 4, 11, ..., 7, 3, 9],
       ...,
       ['T', 6, 9, ..., 12, 2, 4],
       ['S', 2, 3, ..., 9, 5, 8],
       ['A', 4, 9, ..., 7, 2, 8]], dtype=object)

#### Split into train/test 80/20

In [9]:
size = int(0.8*m)
data_train = data[:size]
data_test = data[size:]

data_train = data_train.T
data_test = data_test.T

Y_train = data_train[0]
X_train = data_train[1:]

Y_test = data_test[0]
X_test = data_test[1:]

In [10]:
data_train

array([['T', 'I', 'D', ..., 'G', 'E', 'C'],
       [2, 5, 4, ..., 8, 4, 2],
       [8, 12, 11, ..., 14, 7, 1],
       ...,
       [8, 8, 7, ..., 7, 8, 9],
       [0, 4, 3, ..., 5, 5, 4],
       [8, 10, 9, ..., 8, 8, 10]], dtype=object)

In [11]:
data_test

array([['U', 'N', 'V', ..., 'T', 'S', 'A'],
       [4, 6, 6, ..., 6, 2, 4],
       [10, 9, 9, ..., 9, 3, 9],
       ...,
       [8, 8, 9, ..., 12, 9, 7],
       [5, 0, 7, ..., 2, 5, 2],
       [6, 8, 10, ..., 4, 8, 8]], dtype=object)

In [12]:
Y_train

array(['T', 'I', 'D', ..., 'G', 'E', 'C'], dtype=object)

In [13]:
X_train = X_train.astype(float)
X_train

array([[ 2.,  5.,  4., ...,  8.,  4.,  2.],
       [ 8., 12., 11., ..., 14.,  7.,  1.],
       [ 3.,  3.,  6., ...,  7.,  5.,  3.],
       ...,
       [ 8.,  8.,  7., ...,  7.,  8.,  9.],
       [ 0.,  4.,  3., ...,  5.,  5.,  4.],
       [ 8., 10.,  9., ...,  8.,  8., 10.]])

In [14]:
Y_test

array(['U', 'N', 'V', ..., 'T', 'S', 'A'], dtype=object)

In [15]:
X_test = X_test.astype(float)
X_test

array([[ 4.,  6.,  6., ...,  6.,  2.,  4.],
       [10.,  9.,  9., ...,  9.,  3.,  9.],
       [ 6.,  8.,  8., ...,  6.,  4.,  6.],
       ...,
       [ 8.,  8.,  9., ..., 12.,  9.,  7.],
       [ 5.,  0.,  7., ...,  2.,  5.,  2.],
       [ 6.,  8., 10., ...,  4.,  8.,  8.]])

### Thus we can have an MLP of Architecture 16 -> 128 -> 64 -> 32 -> 26

#### Initializing Parameters

In [16]:
# Using He Init
def init_params():
    W1 = np.random.randn(128,16) * np.sqrt(2/16)
    b1 = np.zeros((128,1))
    W2 = np.random.randn(64,128) * np.sqrt(2/128)
    b2 = np.zeros((64,1))
    W3 = np.random.randn(32,64) * np.sqrt(2/64)
    b3 = np.zeros((32,1))
    W4 = np.random.randn(26,32) * np.sqrt(2/32)
    b4 = np.zeros((26,1))
    
    wArr = [W1,W2,W3,W4]
    bArr = [b1,b2,b3,b4]
    
    return wArr,bArr

#### Utility Functions

In [17]:
def ReLU(Z):
    return np.maximum(Z,0)
    
def derivative_ReLU(Z):
    return Z>0

def softmax(Z):
    expZ = np.exp(Z-np.max(Z,axis = 0, keepdims = True))
    return expZ/np.sum(expZ,axis = 0 ,keepdims = True)
    
def one_hot(Y):
    one_hot_Y = np.zeros((26,Y.size))
    
    for index,value in enumerate(Y):
        one_hot_Y[ord(value)-ord('A')][index] = 1
        
    return one_hot_Y

### Main Functions

In [18]:
def forward_pass(X,wArr,bArr):
    
    #Number of Layers
    n = len(wArr)
    
    activationVal = X
    zArr = []
    aArr = []
    for i in range(n):
        
        zArr.append(wArr[i].dot(activationVal) + bArr[i])
        if i!=n-1:
            activationVal = ReLU(zArr[-1])
            aArr.append(activationVal)
        else:
            activationVal = softmax(zArr[-1])
            aArr.append(activationVal)
            
#     for index,arr in enumerate(aArr):
#         print(index," : ",len(arr),len(arr[0]))
        
    return zArr,aArr

In [19]:
def backward_pass(X,Y,zArr,aArr,wArr):
    
    m = Y.size
    
    #Number of Layers
    n = len(wArr)
    
    dZArr,dWArr,dbArr = [],[],[]
    
    one_hot_Y = one_hot(Y)
    
    for i in range(n):
        
        if i==0:
            dZArr.append(aArr[-1] - one_hot_Y)
        else:
            dZArr.append(wArr[n-i].T.dot(dZArr[-1]) * derivative_ReLU(zArr[n-i-1]))
        
        if i==n-1:
            dWArr.append(1/m * dZArr[-1].dot(X.T))
        else:
            dWArr.append(1/m * dZArr[-1].dot(aArr[n-i-2].T))
            
        dbArr.append(1/m * np.sum(dZArr[-1], axis = 1, keepdims = True))
            
    return dWArr[::-1],dbArr[::-1]

In [20]:
def update_params(alpha,dWArr,dbArr,wArr,bArr):
    
    #Number of Layers
    n = len(wArr)
    
    for i in range(n):
#         print("Debug w : ",len(wArr[i]),"x",len(wArr[i][0]),"Debug dw : ",len(dWArr[i]),"x",len(dWArr[i][0]))
        wArr[i] -= alpha * dWArr[i]
        bArr[i] -= alpha * dbArr[i]
        
    return wArr,bArr

### Driver Function

In [21]:
def get_prediction(A):
    return np.argmax(A,0)

def get_accuracy(prediction,Y):
    #The Y values we get are letters
    digitY = [ord(char)-ord('A') for char in Y]
    
    return np.sum(prediction==digitY)/len(digitY)

def sgd(X,Y,alpha,epochs):
    
    wArr,bArr = init_params()
    batch_size = 100
        
    for epoch_cnt in range(epochs):
        
        shuffled_indices = np.random.permutation(Y.size)
        X_shuffled = X[:, shuffled_indices]
        Y_shuffled = Y[shuffled_indices]
    
        for start in range(0,Y.size,batch_size):

            end = start + batch_size

            X_batch = X_shuffled[:,start:end]
            Y_batch = Y_shuffled[start:end]

            #Perform Forward Pass
            zArr, aArr = forward_pass(X_batch,wArr,bArr)

            #Perform Backward Pass
            dWArr,dbArr = backward_pass(X_batch,Y_batch,zArr,aArr,wArr)

            #Update Parameters
            wArr,bArr = update_params(alpha,dWArr,dbArr,wArr,bArr)
        
        if epoch_cnt%10==0:
            
            print("Epoch : ",epoch_cnt)
            prediction = get_prediction(aArr[-1])
            print(get_accuracy(prediction,Y_batch))
            
    return wArr,bArr

In [22]:
wArr,bArr = sgd(X_train,Y_train,0.02,200)

Epoch :  0
0.24
Epoch :  10
0.85
Epoch :  20
0.91
Epoch :  30
0.83
Epoch :  40
0.85
Epoch :  50
0.93
Epoch :  60
0.92
Epoch :  70
0.94
Epoch :  80
0.98
Epoch :  90
0.93
Epoch :  100
0.96
Epoch :  110
0.94
Epoch :  120
0.94
Epoch :  130
0.98
Epoch :  140
0.96
Epoch :  150
0.97
Epoch :  160
0.95
Epoch :  170
0.93
Epoch :  180
0.98
Epoch :  190
0.99

### 99% ACCURACY !!!!

In [23]:
def make_prediction(X,wArr,bArr):
    
    #Perform Forward Pass
    _,aArr = forward_pass(X,wArr,bArr)
    A = aArr[-1]
    
    return get_prediction(A)

In [24]:
predictions = make_prediction(X_test,wArr,bArr)
print(predictions.size,predictions,Y_test)
get_accuracy(predictions,Y_test)

4000 [20 13 21 ... 19 18  0] ['U' 'N' 'V' ... 'T' 'S' 'A']

0.936

### 93.6% ACCURACY !!!!!!!